name: Oryx
version: 0.05
abstract: Orthogonal Object Persistence
author: Richard Hundt <richard@protea-systems.com>
license: artistic
distribution_type: module
build_requires:
  Test::More: 0
requires:
  perl: 5.6.1
  DBI: YAML
  Class::Data::Inheritable: Class::Date
  SQL::Abstract: Ima::DBI
  DBM::Deep: Data::Types
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
