name: Oryx
version: 0.22
abstract: Object Persistence with Multiple Inheritance
author: Richard Hundt <richard NO SPAM AT protea-systems.com>
license: artistic
distribution_type: module
build_requires:
  YAML: 0
  Class::Observable: 0
  Class::Data::Inheritable: 0
  Class::Date: 0
  DBM::Deep: 0
  Test::More: 0
  Data::Types: 0
  File::Spec: 0
  Module::Pluggable: 0
requires:
  DBI: 0
  YAML: 0
  Class::Observable: 0
  Class::Data::Inheritable: 0
  Class::Date: 0
  SQL::Abstract: 0
  Ima::DBI: 0
  DBM::Deep: 0
  Data::Types: 0
  File::Spec: 0
  Module::Pluggable: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
