name: Oryx
version: 0.17
abstract: Object Persistence with Multiple Inheritance
author: Richard Hundt <richard NO SPAM AT protea-systems.com>
license: artistic
distribution_type: module
build_requires:
  YAML: Class::Data::Inheritable
  Class::Date: DBM::Deep
  Test::More: Data::Types
  File::Spec: Module::Pluggable
requires:
  perl: 5.6.1
  DBI: YAML
  Class::Data::Inheritable: Class::Date
  SQL::Abstract: Ima::DBI
  DBM::Deep: Data::Types
  File::Spec: Module::Pluggable
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
